version: '3'

services:
  ladb:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "127.0.0.1:3366:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=svsla
      - MYSQL_ROOT_PASSWORD=123456789

    laweb:
      build: .
      image: laweb
      restart: always
      command: ["./wait-for", "ladb:3366", "--", "npm", "run", "start:prod" ]
      environment:
        - NODE_ENV=production
        - SERVER_PORT=4444
        - WEB_CONCURRENCY=2
        - DEBUG=express:*
      ports:
        - "80:4444"
      depends_on:
        - ladb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8766:80
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    links:
      - ladb:db
    depends_on:
      - ladb
