version: '3'

services:
  ladb:
    image: mysql:5.7
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - "127.0.0.1:3366:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=svsla
      - MYSQL_ROOT_PASSWORD=123456789

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8766:80
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
    links:
      - ladb:db
    depends_on:
      - ladb